from collections.abc import Sequence
from typing import Any

from cardarena_tournament_core.common.errors import PairingStateError, TournamentCompleteError
from cardarena_tournament_core.common.models import (
    Matchup,
    MatchupOutcome,
    Participant,
    Round,
    participant_from_dict,
    participant_to_dict,
)
from cardarena_tournament_core.pairings.base import BasePairing


class SingleElimination(BasePairing):
    """Single-elimination bracket: lose once and you're out.

    Participants are seeded in the order they are provided.  Round 1 pairs
    seed 1 vs. seed N, seed 2 vs. seed N-1, etc.  Winners advance; losers
    are eliminated.  An odd number of active participants gives the middle
    seed a bye (automatic advancement).
    """

    # -------------------------------------------------------------------------
    # Initialization and configuration
    # -------------------------------------------------------------------------

    def __init__(self, participants: Sequence[Participant]) -> None:
        super().__init__(participants)
        # Original registration order drives deterministic seeding across all rounds.
        self._seeding_order: list[str] = [p.id for p in self._participants]
        self._participant_map: dict[str, Participant] = {p.id: p for p in self._participants}

    # -------------------------------------------------------------------------
    # Pairing / Submission interface
    # -------------------------------------------------------------------------

    def pair(self) -> Round:
        """Generate matchups for the current elimination round.

        Seeds are mirrored: the highest seed plays the lowest, the second
        highest plays the second lowest, and so on.

        Raises:
            TournamentCompleteError: A champion has been determined (one active
                participant remains) or all participants have been eliminated.
        """
        active = [
            self._participant_map[pid]
            for pid in self._seeding_order
            if pid in self._active_ids
        ]

        if len(active) <= 1:
            if len(active) == 1:
                raise TournamentCompleteError(
                    f"{active[0].name} is the champion — the tournament is complete."
                )
            raise TournamentCompleteError("All participants have been eliminated.")

        half = len(active) // 2
        matchups: list[Matchup] = [
            Matchup(player1=active[seed_index], player2=active[len(active) - 1 - seed_index])
            for seed_index in range(half)
        ]

        if len(active) % 2 == 1:
            matchups.append(Matchup(player1=active[half], player2=None))

        round_number = len(self._rounds) + 1
        self._register_round_snapshot(round_number)
        return Round(round_number=round_number, matchups=matchups)

    def submit_results(self, completed_round: Round) -> None:
        """Eliminate losers and update the active participant set.

        The active set after submission is determined entirely by match results —
        winners advance regardless of any ``remove_active_participant`` call made
        after the round was paired.  Manual removal only affects rounds that have
        not yet been generated by ``pair()``.
        """
        winner_ids: list[str] = []
        for matchup in completed_round.matchups:
            if matchup.player2 is None:
                winner_ids.append(matchup.player1.id)
            elif matchup.outcome == MatchupOutcome.PLAYER1_WINS:
                winner_ids.append(matchup.player1.id)
            elif matchup.outcome == MatchupOutcome.PLAYER2_WINS:
                winner_ids.append(matchup.player2.id)
            else:
                raise PairingStateError(
                    "Single elimination matchups must end with PLAYER1_WINS or "
                    "PLAYER2_WINS."
                )

        if not winner_ids:
            raise PairingStateError(
                "Submitting this round produced no advancing participants."
            )

        super().submit_results(completed_round)
        self._active_ids = set(winner_ids)

    # -------------------------------------------------------------------------
    # Serialization and reconstruction
    # -------------------------------------------------------------------------

    @classmethod
    def from_history(
        cls,
        participants: Sequence[Participant],
        rounds: Sequence[Round],
        active_participant_ids: set[str],
    ) -> "SingleElimination":
        """Reconstruct a Single Elimination tournament from its round history.

        Enables stateless operation by rebuilding the active participant set
        from the complete round history. Winners from each round automatically
        advance, but active_participant_ids is always provided to handle manual
        removals between rounds.

        Args:
            participants: All tournament participants in seeding order.
            rounds: Complete round history in chronological order. Each round
                   must have all outcomes recorded (is_complete == True).
            active_participant_ids: Set of participant IDs currently eligible
                                   for pairing. Always provided by design.

        Returns:
            SingleElimination instance with state matching the provided history.

        Raises:
            PairingConfigurationError: Invalid configuration parameters.
            PairingStateError: Round history is invalid (incomplete rounds,
                              unknown participants, out-of-order rounds, or
                              active_participant_ids contains unknown IDs).

        Example:
            >>> elimination = SingleElimination.from_history(
            ...     participants=[participant_from_dict(p) for p in data["participants"]],
            ...     rounds=[Round.from_dict(r) for r in data["rounds"]],
            ...     active_participant_ids=set(data["active_participant_ids"]),
            ... )
            >>> next_round = elimination.pair()
        """
        # Create fresh instance with initial state
        instance = cls(participants=participants)

        # Replay all rounds to rebuild active set from winners
        for round_obj in rounds:
            # STRICT VALIDATION: Fail fast on incomplete rounds
            if not round_obj.is_complete:
                raise PairingStateError(
                    f"Cannot reconstruct from incomplete round {round_obj.round_number}. "
                    f"All rounds must have recorded outcomes."
                )

            # submit_results will:
            # 1. Validate round integrity (sequential numbering, valid participants)
            # 2. Determine winners from matchup outcomes
            # 3. Update _active_ids to only include winners
            # 4. Append to _rounds history
            instance.submit_results(round_obj)

        # STRICT VALIDATION: Verify all active IDs are registered participants
        unknown_ids = active_participant_ids - instance._participant_ids
        if unknown_ids:
            raise PairingStateError(
                f"active_participant_ids contains unregistered participants: "
                f"{', '.join(sorted(unknown_ids))}"
            )

        # Override with provided active set (handles manual removals between rounds)
        instance._active_ids = set(active_participant_ids)

        return instance

    def to_dict(self) -> dict[str, Any]:
        """Export tournament state for persistence.

        Returns:
            Dictionary with keys:
            - participants: List of participant dicts (in seeding order)
            - rounds: List of round dicts
            - active_participant_ids: Sorted list of active participant IDs
        """
        return {
            "participants": [participant_to_dict(p) for p in self._participants],
            "rounds": [r.to_dict() for r in self._rounds],
            "active_participant_ids": sorted(self._active_ids),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SingleElimination":
        """Reconstruct tournament from serialized state.

        Args:
            data: Dictionary from to_dict() or database.

        Returns:
            Reconstructed SingleElimination instance.
        """
        participants = [participant_from_dict(p) for p in data["participants"]]
        rounds = [Round.from_dict(r) for r in data["rounds"]]
        active_ids = set(data["active_participant_ids"])

        return cls.from_history(
            participants=participants,
            rounds=rounds,
            active_participant_ids=active_ids,
        )