"""Shared errors and data models for the tournament core package."""

from cardarena_tournament_core.common.errors import (
    CardArenaError,
    ConfigurationError,
    IncompleteRoundError,
    MatchupValidationError,
    PairingConfigurationError,
    PairingStateError,
    ParticipantValidationError,
    RoundValidationError,
    ScoringError,
    ScoringValidationError,
    StandingValidationError,
    StateError,
    TeamValidationError,
    TournamentCompleteError,
    TournamentConfigurationError,
    ValidationError,
)
from cardarena_tournament_core.common.models import (
    Matchup,
    MatchupOutcome,
    Participant,
    Player,
    Round,
    Standing,
    Team,
    participant_from_dict,
    participant_to_dict,
)

__all__ = [
    "CardArenaError",
    "ConfigurationError",
    "ValidationError",
    "StateError",
    "ParticipantValidationError",
    "TeamValidationError",
    "MatchupValidationError",
    "RoundValidationError",
    "StandingValidationError",
    "TournamentConfigurationError",
    "PairingConfigurationError",
    "PairingStateError",
    "TournamentCompleteError",
    "ScoringError",
    "ScoringValidationError",
    "IncompleteRoundError",
    "Player",
    "Team",
    "Participant",
    "Matchup",
    "MatchupOutcome",
    "Round",
    "Standing",
    "participant_to_dict",
    "participant_from_dict",
]